/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha1.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.kabanero.v1alpha1.models.CollectionStatusActivePipelines;
import io.kabanero.v1alpha1.models.CollectionStatusImages;
import io.kabanero.v1alpha1.models.CollectionStatusVersions;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CollectionStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-23T16:26:35.229Z[Etc/UTC]")
public class CollectionStatus {
  public static final String SERIALIZED_NAME_ACTIVE_LOCATION = "activeLocation";
  @SerializedName(SERIALIZED_NAME_ACTIVE_LOCATION)
  private String activeLocation;

  public static final String SERIALIZED_NAME_ACTIVE_PIPELINES = "activePipelines";
  @SerializedName(SERIALIZED_NAME_ACTIVE_PIPELINES)
  private List<CollectionStatusActivePipelines> activePipelines = null;

  public static final String SERIALIZED_NAME_ACTIVE_VERSION = "activeVersion";
  @SerializedName(SERIALIZED_NAME_ACTIVE_VERSION)
  private String activeVersion;

  public static final String SERIALIZED_NAME_AVAILABLE_LOCATION = "availableLocation";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_LOCATION)
  private String availableLocation;

  public static final String SERIALIZED_NAME_AVAILABLE_VERSION = "availableVersion";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_VERSION)
  private String availableVersion;

  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<CollectionStatusImages> images = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATUS_MESSAGE = "statusMessage";
  @SerializedName(SERIALIZED_NAME_STATUS_MESSAGE)
  private String statusMessage;

  public static final String SERIALIZED_NAME_VERSIONS = "versions";
  @SerializedName(SERIALIZED_NAME_VERSIONS)
  private List<CollectionStatusVersions> versions = null;


  public CollectionStatus activeLocation(String activeLocation) {
    
    this.activeLocation = activeLocation;
    return this;
  }

   /**
   * Get activeLocation
   * @return activeLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getActiveLocation() {
    return activeLocation;
  }


  public void setActiveLocation(String activeLocation) {
    this.activeLocation = activeLocation;
  }


  public CollectionStatus activePipelines(List<CollectionStatusActivePipelines> activePipelines) {
    
    this.activePipelines = activePipelines;
    return this;
  }

  public CollectionStatus addActivePipelinesItem(CollectionStatusActivePipelines activePipelinesItem) {
    if (this.activePipelines == null) {
      this.activePipelines = new ArrayList<CollectionStatusActivePipelines>();
    }
    this.activePipelines.add(activePipelinesItem);
    return this;
  }

   /**
   * Get activePipelines
   * @return activePipelines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CollectionStatusActivePipelines> getActivePipelines() {
    return activePipelines;
  }


  public void setActivePipelines(List<CollectionStatusActivePipelines> activePipelines) {
    this.activePipelines = activePipelines;
  }


  public CollectionStatus activeVersion(String activeVersion) {
    
    this.activeVersion = activeVersion;
    return this;
  }

   /**
   * Get activeVersion
   * @return activeVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getActiveVersion() {
    return activeVersion;
  }


  public void setActiveVersion(String activeVersion) {
    this.activeVersion = activeVersion;
  }


  public CollectionStatus availableLocation(String availableLocation) {
    
    this.availableLocation = availableLocation;
    return this;
  }

   /**
   * Get availableLocation
   * @return availableLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAvailableLocation() {
    return availableLocation;
  }


  public void setAvailableLocation(String availableLocation) {
    this.availableLocation = availableLocation;
  }


  public CollectionStatus availableVersion(String availableVersion) {
    
    this.availableVersion = availableVersion;
    return this;
  }

   /**
   * Get availableVersion
   * @return availableVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAvailableVersion() {
    return availableVersion;
  }


  public void setAvailableVersion(String availableVersion) {
    this.availableVersion = availableVersion;
  }


  public CollectionStatus images(List<CollectionStatusImages> images) {
    
    this.images = images;
    return this;
  }

  public CollectionStatus addImagesItem(CollectionStatusImages imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<CollectionStatusImages>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CollectionStatusImages> getImages() {
    return images;
  }


  public void setImages(List<CollectionStatusImages> images) {
    this.images = images;
  }


  public CollectionStatus status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public CollectionStatus statusMessage(String statusMessage) {
    
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatusMessage() {
    return statusMessage;
  }


  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }


  public CollectionStatus versions(List<CollectionStatusVersions> versions) {
    
    this.versions = versions;
    return this;
  }

  public CollectionStatus addVersionsItem(CollectionStatusVersions versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<CollectionStatusVersions>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Get versions
   * @return versions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CollectionStatusVersions> getVersions() {
    return versions;
  }


  public void setVersions(List<CollectionStatusVersions> versions) {
    this.versions = versions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionStatus {\n");
    sb.append("    activeLocation: ").append(toIndentedString(activeLocation)).append("\n");
    sb.append("    activePipelines: ").append(toIndentedString(activePipelines)).append("\n");
    sb.append("    activeVersion: ").append(toIndentedString(activeVersion)).append("\n");
    sb.append("    availableLocation: ").append(toIndentedString(availableLocation)).append("\n");
    sb.append("    availableVersion: ").append(toIndentedString(availableVersion)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

