/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kabanero.v1alpha1.models;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Kabanero Application Navigator instance readiness status.
 */
@ApiModel(description = "Kabanero Application Navigator instance readiness status.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-23T14:21:52.747Z[Etc/UTC]")
public class KabaneroStatusKappnav {
  public static final String SERIALIZED_NAME_API_LOCATIONS = "apiLocations";
  @SerializedName(SERIALIZED_NAME_API_LOCATIONS)
  private List<String> apiLocations = null;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "errorMessage";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  private String errorMessage;

  public static final String SERIALIZED_NAME_READY = "ready";
  @SerializedName(SERIALIZED_NAME_READY)
  private String ready;

  public static final String SERIALIZED_NAME_UI_LOCATIONS = "uiLocations";
  @SerializedName(SERIALIZED_NAME_UI_LOCATIONS)
  private List<String> uiLocations = null;


  public KabaneroStatusKappnav apiLocations(List<String> apiLocations) {
    
    this.apiLocations = apiLocations;
    return this;
  }

  public KabaneroStatusKappnav addApiLocationsItem(String apiLocationsItem) {
    if (this.apiLocations == null) {
      this.apiLocations = new ArrayList<String>();
    }
    this.apiLocations.add(apiLocationsItem);
    return this;
  }

   /**
   * Get apiLocations
   * @return apiLocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getApiLocations() {
    return apiLocations;
  }


  public void setApiLocations(List<String> apiLocations) {
    this.apiLocations = apiLocations;
  }


  public KabaneroStatusKappnav errorMessage(String errorMessage) {
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getErrorMessage() {
    return errorMessage;
  }


  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public KabaneroStatusKappnav ready(String ready) {
    
    this.ready = ready;
    return this;
  }

   /**
   * Get ready
   * @return ready
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReady() {
    return ready;
  }


  public void setReady(String ready) {
    this.ready = ready;
  }


  public KabaneroStatusKappnav uiLocations(List<String> uiLocations) {
    
    this.uiLocations = uiLocations;
    return this;
  }

  public KabaneroStatusKappnav addUiLocationsItem(String uiLocationsItem) {
    if (this.uiLocations == null) {
      this.uiLocations = new ArrayList<String>();
    }
    this.uiLocations.add(uiLocationsItem);
    return this;
  }

   /**
   * Get uiLocations
   * @return uiLocations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getUiLocations() {
    return uiLocations;
  }


  public void setUiLocations(List<String> uiLocations) {
    this.uiLocations = uiLocations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    return EqualsBuilder.reflectionEquals(this, o);
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(this);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoKabaneroV1alpha1KabaneroStatusKappnav {\n");
    sb.append("    apiLocations: ").append(toIndentedString(apiLocations)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    uiLocations: ").append(toIndentedString(uiLocations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

